# Generated by Django 4.0.7 on 2023-01-09 19:34

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('techs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='tech',
            name='tech_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tech',
            name='techs',
            field=models.ManyToManyField(related_name='techs', to=settings.AUTH_USER_MODEL),
        ),
    ]
