# Generated by Django 4.0.7 on 2023-01-09 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0003_rename_techs_tech_users_alter_tech_tech_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='users',
        ),
    ]
