# Generated by Django 4.0.7 on 2023-01-10 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0005_alter_tech_tech_name'),
        ('posts', '0004_post_techs_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='techs',
        ),
        migrations.AddField(
            model_name='post',
            name='tech',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='techs.tech'),
            preserve_default=False,
        ),
    ]
