# Generated by Django 4.0.7 on 2023-01-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techs', '0004_remove_tech_users'),
        ('users', '0011_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='techs',
            field=models.ManyToManyField(related_name='users', to='techs.tech'),
        ),
    ]
