# Generated by Django 4.0.7 on 2023-01-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firepost',
            name='post',
            field=models.IntegerField(max_length=100),
        ),
    ]
