# Generated by Django 4.0.7 on 2023-01-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0003_rename_user_firepost_user_id_alter_firepost_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='firepost',
            name='teste',
            field=models.BooleanField(null=True),
        ),
    ]
