# Generated by Django 4.0.7 on 2023-01-04 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0004_firepost_teste'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firepost',
            old_name='teste',
            new_name='exists',
        ),
    ]
