# Generated by Django 4.0.7 on 2023-01-04 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0005_rename_teste_firepost_exists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firepost',
            name='exists',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
