# Generated by Django 4.0.7 on 2023-01-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fires', '0006_alter_firepost_exists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firepost',
            name='post',
        ),
        migrations.RemoveField(
            model_name='firepost',
            name='user_id',
        ),
        migrations.AddField(
            model_name='firecomments',
            name='exists',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
