# Generated by Django 4.0.7 on 2023-01-10 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_post_techs_post_user'),
        ('fires', '0008_firepost_post_firepost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firepost',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fires', to='posts.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firepost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fires', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
