# Generated by Django 4.0.7 on 2023-01-10 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_post_comment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fires', '0009_alter_firepost_post_alter_firepost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='firecomments',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fires', to='comments.comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='firecomments',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fires_comments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='firepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fires_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
